# 1.Slip the String

In [1]:
s = "Hi there Sam";

In [2]:
s=s.split()

In [3]:
print(s);

['Hi', 'there', 'Sam']


# 2. Use .format() to print the following string.

In [4]:
plant = "Earth"

In [5]:
diameter = 12742

In [7]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [9]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [10]:
a=lst[3][1][2];

In [11]:
print(a)

['hello']


**Numpy**

In [12]:
import numpy as np

# 4.1 Create an array of 10 zeros?

In [13]:
import numpy as np

In [14]:
array=np.zeros(10)

In [15]:
print("An array of 10zero")

An array of 10zero


In [16]:
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4.2 Create an array of 10 fives?

In [17]:
import numpy as np

In [18]:
array = np.ones(10)*5

In [19]:
print("An array of 10 five")

An array of 10 five


In [20]:
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [21]:
import numpy as np

In [22]:
array=np.arange(20,35,2)

In [23]:
print("Array of all the even integers from 20 to 35")

Array of all the even integers from 20 to 35


In [24]:
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
import numpy as np

In [26]:
x = np.arange(0, 9).reshape(3,3)

In [27]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7. Concatinate a and b
a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [28]:
import numpy as np

In [29]:
a = np. array ([1,2,3])

In [30]:
b = np. array ([4,5,6])

In [31]:
c = np.concatenate((a,b))

In [32]:
print(c)

[1 2 3 4 5 6]


Pandas

In [33]:
import pandas as pd

# 8. Create a dataframe with 3 rows and 2 columns

In [34]:
data = [['TOM', 20], ['NICK', 21], ['KRISH', 14], ['JACK', 18]]

In [35]:
df = pd.DataFrame(data, columns=['Name', 'Age'])

In [36]:
df

Name  Age
0    TOM   20
1   NICK   21
2  KRISH   14
3   JACK   18

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [37]:
import pandas as pd

In [38]:
dRan1 = pd.date_range(start ='1-1-2023', periods = 41)
print(dRan1)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


# 10. Create 2D list to DataFrame

In [39]:
import pandas as pd

In [40]:
import numpy as np

In [41]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [42]:
list= {'name':['aaa', 'bbb', 'ccc'],
'points':[22,25,24]}

In [43]:
df = pd.DataFrame(list,index=['1','2','3'])

In [44]:
df

name  points
1  aaa      22
2  bbb      25
3  ccc      24